name: "Test"
on:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v22
      - uses: workflow/nix-shell-action@v3
        with:
          flakes-from-devshell: true
          script: |
            meson setup build
            ninja -C build
